export interface Device {
    admdongCd: string
    barcode: string
    buyerMbrSeq: string
    comType: string
    dvcAuthCd: string
    dvcAuthReasonCd: string
    dvcBrandCd: string
    dvcModel: string
    dvcNick: string
    dvcRegStatCd: string
    dvcSeq: number
    dvcTypeCd: string
    eUseTp: string
    gpsLat: string
    gpsLng: string
    gpsNationCd: string
    guideTypeCd: string
    heartsvcDttm: string
    instDttm: string
    instYn: string
    installAddr: string
    iotYn: string
    isGubun: string
    mbrDvcSeq: number
    membershipYn: string
    netStatus: boolean
    ordNo: string
    pairingDttm: string
    prodCd: string
    prodName: string
    prodNameFull: string
    prodType: string
    regDttm: string
    registUserCount: number
    releaseDttm: string
    resetDttm: string
    roomPos: string
    rqDttm: string
    rq_stat_cd: string
    salesCntryId: string
    selfManageYn: string
    sellTypeCd: string
    sort: number
    stationCd: string
    unreadYN: string
    userGradeCd: string
    userTypeCd: string
    wifiType: string
    userGrade: string
    managerYn: string
    registAllCount: number
    mbrSeq: string
}
